# Generated by Django 2.2.5 on 2019-09-19 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190918_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, null=True, unique=True)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Hign'), (0, 'Middle'), (-1, 'Low')])),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (0, 'Uncompleted')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='tasks.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
