# Generated by Django 2.2.5 on 2019-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Hign'), (0, 'Middle'), (-1, 'Low')], default=1),
        ),
    ]
