# Generated by Django 2.2.2 on 2019-09-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_test',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
